### ISSUE TITLE
Does the network viewer work on 1.3.2?

### ISSUE THREAD

**Issue by hsauro** [sys-bio/tellurium#118]
I can't get the network viewer plugin to work in 1.3.2. If I try to click on the load sbml model button I get:

Traceback (most recent call last):
  File "C:\Tellurium-Winpython\python-2.7.10\lib\site-packages\pyfab_app.py", line 459, in save
    if self.openfilepath:
AttributeError: 'PyfabPlugin' object has no attribute 'openfilepath'

Also if I call :

sbnw.loadsbml (r.getSBML())
Out[88]: <sbnw.sbmlmodel at 0x1364e758>

Nothing appears on the viewer.

**Comment by 0u812** [comment]
I take it this is the Windows version? Kiri, one thing to check would be the files under the spyderlib directory of the sbnw installation. They need to be copied into spyder's spyderlib directory.

This is also another reason we should abandon the manual installers. We have to maintain a fork of spyder to make these changes persistent. I can't take on something like that. Kiri, maybe you can maintain a fork of spyder?

On April 5, 2016 8:01:33 PM GMT+02:00, Herbert Sauro <notifications@github.com> wrote:
>I can't get the network viewer plugin to work in 1.3.2. If I try to
>click on the load sbml model button I get:
>
>Traceback (most recent call last):
>File
>"C:\Tellurium-Winpython\python-2.7.10\lib\site-packages\pyfab_app.py",
>line 459, in save
>    if self.openfilepath:
>AttributeError: 'PyfabPlugin' object has no attribute 'openfilepath'
>
>Also if I call :
>
>sbnw.loadsbml (r.getSBML())
>Out[88]: <sbnw.sbmlmodel at 0x1364e758>
>
>Nothing appears on the viewer.
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/sys-bio/tellurium/issues/118

-- 
Sent from my TARDIS with K-9 Mail. Wibbly-wobbly wordy gurdy.

**Comment by hsauro** [comment]
Better have this fixed soon if it s a problem because the reviewers see it.

Kiri, you maintain the windows installer, can you fix it?

As for installers, on Windows at least I want Tellurium to be as easy to
install as it Copasi. For Linux (especially) and Mac, the conda way is ok.

Herbert

**Comment by kirichoi** [comment]
I am working on it right now.

Kiri

**Comment by kirichoi** [comment]
It seems fine to me. Could you double check? I see in the error there is a part saying `in save` which means that you might have pressed save button instead. It that's the case, the output is normal I believe because there is nowhere to save things to.

**Comment by hsauro** [comment]
I'll reinstall to see if that helps.

H
